# S3 纸牌小游戏：补充翻译提取器未收录的问题卡、答案卡和动态反应。

init 1004 python:
    _s3_card_game_prev_replace_text = config.replace_text
    _s3_card_game_cn_exact = {
        "Violent diarrhea.": "严重腹泻。",
        "Too many orgasms.": "高潮太多。",
        "A crusty cum sock.": "一只结满精斑的袜子。",
        "Gay porn.": "男同性恋色情片。",
        "A finger in the anus.": "插进肛门的一根手指。",
        "Nothing.": "什么都没有。",
        "A short adventure.": "一场短暂的冒险。",
        "Ok, Grandpa. Let's get you to bed.": "好了，爷爷，该送你上床了。",
        "Birthday cake.": "生日蛋糕。",
        "Your girlfriend.": "你的女朋友。",
        "STDs.": "性病。",
        "Building sandcastles.": "堆沙堡。",
        "A microwave.": "一台微波炉。",
        "Mayonnaise.": "蛋黄酱。",
        "Brown stuff.": "棕色的东西。",
        "Your mom.": "你妈妈。",
        "Yatzy!": "快艇骰子！",
        "Laughter.": "笑声。",
        "Sperm.": "精子。",
        "Snorting cocaine.": "吸食可卡因。",
        "What's the best cure for depression?": "治疗抑郁的最佳方法是什么？",
        "An apple.": "一个苹果。",
        "Drinking all night long.": "喝上一整夜。",
        "A big black cock.": "一根黑人的大鸡巴。",
        "Dancing the night away.": "彻夜跳舞。",
        "Vaseline.": "凡士林。",
        "Money.": "钱。",
        "Spaghetti.": "意大利面。",
        "A fistful of parsley.": "一大把欧芹。",
        "Tiny hats.": "迷你帽子。",
        "What's my favorite hobby? I won't tell you exactly what it is, but it involves...": "我最喜欢的爱好是什么？不直接告诉你，但它需要……",
        "Two condoms.": "两个避孕套。",
        "Grandma.": "奶奶。",
        "Lube.": "润滑液。",
        "Doing things.": "做些事情。",
        "A bowl of fruit.": "一碗水果。",
        "A human pyramid.": "叠罗汉。",
        "Getting drunk.": "喝醉。",
        "Talking to strangers.": "和陌生人说话。",
        "A wet tongue.": "湿漉漉的舌头。",
        "What do I want to do tonight? It's simple. You, me, and...": "我今晚想做什么？很简单：你、我，还有……",
        "Eight other dudes.": "另外八个男人。",
        "Tequila.": "龙舌兰酒。",
        "Butt stuff.": "屁股玩法。",
        "My belly button.": "我的肚脐。",
        "Shredding top-secret documents.": "粉碎绝密文件。",
        "Screaming in libraries.": "在图书馆里大喊大叫。",
        "An encyclopedia.": "一本百科全书。",
        "A bouncy castle.": "充气城堡。",
        "69.": "69式。",
        "What's the title of my sex tape?": "我的性爱录像叫什么名字？",
        "My mom's friend Susan.": "我妈妈的朋友苏珊。",
        "A filthy pig.": "一头肮脏的猪。",
        "Riding a horse.": "骑马。",
        "Disappointment.": "失望。",
        "Tears of joy.": "喜悦的泪水。",
        "My first time.": "我的第一次。",
        "Getting wet.": "湿透了。",
        "Ketchup on a wiener.": "香肠上挤番茄酱。",
        "Butt sex.": "肛交。",
        "Do you know what would liven up this party?": "知道什么能让派对热闹起来吗？",
        "An inappropriate cluck on Rooster.": "Rooster上一条不雅的帖子。",
        "Poop.": "大便。",
        "Naughty girls.": "坏女孩。",
        "Free Wi-Fi.": "免费Wi-Fi。",
        "Absolute silence.": "绝对的安静。",
        "A monkey.": "一只猴子。",
        "A juicy orange.": "一个多汁的橙子。",
        "Estrogen.": "雌激素。",
        "Low inhibitions.": "放下矜持。",
        "Today's youth are spoiled. When I was young, all I had to play with was...": "现在的年轻人都被惯坏了。我小时候只有……可以玩。",
        "My left hand.": "我的左手。",
        "Boogers.": "鼻屎。",
        "Boner.": "勃起的鸡巴。",
        "My brother.": "我兄弟。",
        "A million dollars.": "一百万美元。",
        "Marbles.": "弹珠。",
        "A bucket.": "一个水桶。",
        "A banana.": "一根香蕉。",
        "Mustard.": "芥末酱。",
        "What do you dream of doing when you get older?": "你长大后梦想做什么？",
        "My boss's wife.": "我老板的妻子。",
        "Naked parachuting.": "裸体跳伞。",
        "Shaving my balls.": "刮睾毛。",
        "Driving too slow to piss people off.": "故意开得很慢气死别人。",
        "Smiling when you feel dead inside.": "心如死灰时还保持微笑。",
        "A night in jail.": "在监狱里过一夜。",
        "Posting awesome memes.": "发布绝妙的梗图。",
        "A wicked backflip.": "一个漂亮的后空翻。",
        "Being horny all the time.": "永远欲火焚身。",
        "What do you give to a man who has it all?": "该送什么给一个什么都不缺的男人？",
        "Syphilis.": "梅毒。",
        "A spleen.": "一个脾脏。",
        "AIDS.": "艾滋病。",
        "A high five.": "击个掌。",
        "Peace and love.": "和平与爱。",
        "Three tomatoes and an onion.": "三个西红柿和一个洋葱。",
        "A warm smile.": "一个温暖的微笑。",
        "Ginger ale.": "姜汁汽水。",
        "Unpaid parking tickets.": "没交罚款的停车罚单。",
        "Stop it! You and your sister are both great, but at different things. She's good at socializing. You're good at...": "别争了！你和姐姐都很棒，只是各有所长。她擅长社交，而你擅长……",
        "A blowjob.": "口交。",
        "Masturbating.": "自慰。",
        "Farting.": "放屁。",
        "Juggling.": "杂耍。",
        "Drinking water.": "喝水。",
        "Failing tests.": "考试不及格。",
        "Doing cartwheels.": "侧手翻。",
        "Fucking things up.": "把事情搞砸。",
        "Eating lasagna.": "吃千层面。",
        "What's the secret to a happy relationship?": "幸福感情的秘诀是什么？",
        "That Swyper account you said you deleted.": "你声称已经删除的Swyper账号。",
        "Coughing to cover up your fart.": "用咳嗽掩盖屁声。",
        "Alcohol.": "酒精。",
        "Silently nodding while zoning out.": "心不在焉地默默点头。",
        "Optimism.": "乐观。",
        "Being sassy.": "毒舌。",
        "Tofu.": "豆腐。",
        "Shutting the fuck up.": "他妈的闭嘴。",
        "Having an affair.": "婚外情。",
        "If that mockingbird don't sing, Mama's gonna buy you...": "如果知更鸟不唱歌，妈妈就给你买……",
        "A trip to Thailand.": "一次泰国之旅。",
        "A fucking goat.": "一只该死的山羊。",
        "A double-headed dildo.": "双头假阳具。",
        "A cat.": "一只猫。",
        "Therapy.": "心理治疗。",
        "A hamster.": "一只仓鼠。",
        "A jar of jam.": "一罐果酱。",
        "A hammer.": "一把锤子。",
        "A bucket of coleslaw.": "一桶凉拌卷心菜。",
        "How do you know when a date is not for you? When they start talking about...": "怎么判断约会对象不适合你？当对方开始谈论……",
        "Children.": "孩子。",
        "Sobriety.": "戒酒。",
        "Waterboarding.": "水刑。",
        "Shaving your cat.": "给猫剃毛。",
        "Setting things on fire for fun.": "以纵火为乐。",
        "Quantum physics.": "量子物理。",
        "An ex-boyfriend.": "前男友。",
        "A poem about your reproductive organ.": "一首歌颂你生殖器的诗。",
        "Pineapple on pizza.": "披萨上的菠萝。",
        "I failed the class. My professor didn't enjoy my essay on...": "我这门课挂了。教授不喜欢我那篇关于……的论文。",
        "Boobs.": "奶子。",
        "Dingleberries.": "屁股上的屎渣。",
        "Doing it doggystyle.": "后入式做爱。",
        "The alphabet.": "字母表。",
        "Braille.": "盲文。",
        "The best reality shows on TV.": "电视上最棒的真人秀。",
        "Wet dreams.": "春梦。",
        "Gloryholes.": "墙洞口交。",
        "People I don't like.": "我讨厌的人。",
        "At my college we don't play rock, paper, scissors. We play rock, paper...": "我们大学不玩石头剪刀布，而是玩石头、布……",
        "Dildo.": "假阳具。",
        "A fanny kiss.": "亲屁股。",
        "Fart.": "放屁。",
        "A garden hose.": "花园水管。",
        "MEOW!": "喵！",
        "Pencils.": "铅笔。",
        "A smelly fish.": "一条臭鱼。",
        "Fuck you.": "去你的。",
        "Camel toe.": "骆驼趾。",
        "All I got for Christmas was...": "我圣诞节只收到了……",
        "Herpes.": "疱疹。",
        "An awkward conversation about birds and bees.": "一场尴尬的性启蒙谈话。",
        "A fingernail.": "一片指甲。",
        "A hug.": "一个拥抱。",
        "A song.": "一首歌。",
        "A balloon animal.": "气球动物。",
        "Sympathy.": "同情。",
        "Anxiety.": "焦虑。",
        "An empty box.": "一个空盒子。",
        "Thank you for the award, but I couldn't have done this by myself. I got a little help from...": "谢谢这个奖，但我无法独自做到。我还得到了一点来自……的帮助。",
        "Vodka.": "伏特加。",
        "Cocaine.": "可卡因。",
        "An imaginary friend.": "一个想象中的朋友。",
        "My dog.": "我的狗。",
        "The entire internet.": "整个互联网。",
        "People.": "人类。",
        "A Chinese woman.": "一个中国女人。",
        "Sexual education.": "性教育。",
        "My pet rock.": "我的宠物石头。",
        "Instead of donating money to third-world countries, we will donate...": "我们不向第三世界国家捐钱，而是捐赠……",
        "A funny joke.": "一个好笑的笑话。",
        "The homeless.": "无家可归者。",
        "Sand.": "沙子。",
        "Two dollars.": "两美元。",
        "Rooster likes.": "Rooster点赞。",
        "Breakfast.": "早餐。",
        "A prayer.": "一次祈祷。",
        "Breast milk.": "母乳。",
        "Leftovers.": "剩饭。",
        "The winner of the competition receives $1000. The prize for the runner-up is...": "比赛冠军可得1000美元，亚军奖品是……",
        "A mischievous little slut.": "一个顽皮的小骚货。",
        "A weekend with me.": "和我共度一个周末。",
        "A fist bump.": "碰个拳。",
        "$2000.": "2000美元。",
        "Spanish lessons.": "西班牙语课程。",
        "A hip hip hooray!": "三声万岁！",
        "A hickey.": "一个吻痕。",
        "22 hot shots.": "22杯烈酒。",
        "A wooden stick.": "一根木棍。",
        "How the date went? It started off with a candlelit dinner and ended with...": "约会怎么样？以烛光晚餐开始，以……结束。",
        "A wet willy.": "湿手指掏耳朵。",
        "A house fire.": "一场房屋火灾。",
        "Peekaboo!": "躲猫猫！",
        "Dinner.": "晚餐。",
        "Dessert.": "甜点。",
        "A handshake.": "一次握手。",
        "Mexico.": "墨西哥。",
        "Sex.": "做爱。",
        "Thumb wars.": "拇指大战。",
        "What's not appropriate for Show and Tell?": "什么东西不适合带到课堂展示？",
        "A butt plug.": "肛塞。",
        "A beer bong.": "啤酒漏斗。",
        "Making babies.": "造小孩。",
        "Confetti.": "彩纸屑。",
        "Moonshine.": "私酿烈酒。",
        "A bunch of fireworks.": "一大堆烟花。",
        "A hobo.": "一个流浪汉。",
        "A diaper.": "一片尿布。",
        "Russian roulette.": "俄罗斯轮盘赌。",
        "HAHA! Vaseline and what...?": "哈哈！凡士林，还要什么……？",
        "BAHAHA! That wouldn't cure me!": "哈哈哈！那可治不好我！",
        "Cheers! That could work.": "干杯！这也许管用。",
        "Hahaha! That's so stupid!": "哈哈哈！太蠢了！",
        "Haha! I guess it depends on what you do with it.": "哈哈！那要看你拿它做什么。",
        "Hahaha! I don't think it is! But I bet it makes you forget about the depression for a while.": "哈哈哈！我觉得不行！不过它肯定能让你暂时忘掉抑郁。",
        "Haha! Why spaghetti?": "哈哈！为什么是意大利面？",
        "What a shitty cure. Literally.": "真是个屎一样的疗法，字面意义上的。",
        "Hahaha! Why is that funny?": "哈哈哈！这为什么会好笑？",
        "Hahaha! Corny but hilarious! It's the best medicine, after all.": "哈哈哈！俗是俗了点，但真好笑！毕竟笑是最好的良药。",
        "Haha! It's probably true.": "哈哈！说不定真是这样。",
        "Hahaha! Now, there's bad advice, and there's {b}bad{/b} advice.": "哈哈哈！有馊主意，也有{b}烂透了{/b}的主意。",
        "Haha! We should have bought those for this party.": "哈哈！早知道该给这场派对买几顶。",
        "Haha! Yes. Man... I envy girls. If I were a girl, I'd cum so many times.": "哈哈！没错。天啊……真羡慕女孩。我要是女孩，一定高潮个没完。",
        "Hahaha! That's so stupid, but it would make me feel happier.": "哈哈哈！太蠢了，不过确实会让我开心点。",
        "Hahaha! You can't tell me what it is? But building sandcastles is very specific.": "哈哈哈！不能告诉我是什么？可堆沙堡已经说得很具体了。",
        "Hahaha! What fucking hobby would that be?": "哈哈哈！那他妈是什么爱好？",
        "Hahaha! So gross! What could that hobby even be?": "哈哈哈！太恶心了！那到底是什么爱好？",
        "Haha. Yeah, if I had a shitload of cash, I sure wouldn't be depressed.": "哈哈。对，要是我有一大笔钱，肯定不会抑郁。",
        "Haha! Man's best friend, am I right?": "哈哈！人类最好的朋友，对吧？",
        "Why do I feel like Derek played this one?": "我怎么觉得这张是Derek出的？",
        "Hahaha! Yay!": "哈哈哈！好耶！",
        "Hahaha! I've got more questions after hearing that answer.": "哈哈哈！听完这答案，我的问题反而更多了。",
        "Hahaha! Sign me up for that hobby!": "哈哈哈！这爱好算我一个！",
        "Haha! Yeah, no shit.": "哈哈！对，可不是嘛。",
        "Haha! Sign me up for some lesbian porn.": "哈哈！女同性恋色情片算我一个。",
        "Haha! Doing what?": "哈哈！做什么事？",
        "Haha! What the hell are we going to do with mayo?": "哈哈！我们拿蛋黄酱干什么？",
        "Hah! That's naughty.": "哈！真够坏的。",
        "Haha! Whatever that is, it's good that it's just a hobby and not a profession.": "哈哈！不管那是什么，幸好只是爱好，不是职业。",
        "A bowl of fruit? What? Why?": "一碗水果？什么？为什么？",
        "HAHA! It depends on whose finger.": "哈哈！那得看是谁的手指。",
        "Haha! Two?": "哈哈！两个？",
        "Hahaha! How short are we talking about?": "哈哈哈！到底有多短？",
        "Haha! Yes, I'll be your partner in crime. Sign me up!": "哈哈！好啊，我来当你的共犯。算我一个！",
        "Haha! What a wild night that would be.": "哈哈！那一晚肯定疯透了。",
        "Nerd alert.": "书呆子警报。",
        "BAHAHA! Like a human finger puppet.": "哈哈哈！像个人肉手指玩偶。",
        "Haha! I don't want to know what you'd do with Grandma.": "哈哈！我可不想知道你要和奶奶做什么。",
        "Haha! That fits in perfectly!": "哈哈！这答案太合适了！",
        "Hahaha! The only one I'm sure didn't play this card is Maya.": "哈哈哈！唯一可以确定没出这张牌的人就是Maya。",
        "Top-notch comedy. Haha!": "顶级喜剧。哈哈！",
        "Haha! Stay away from my belly button.": "哈哈！离我的肚脐远点。",
        "HAHA! Sounds like a best seller!": "哈哈！听起来一定会大卖！",
        "Hahaha! Yes! That sounds like a perfect night!": "哈哈哈！对！听起来是个完美之夜！",
        "Hahaha! That's clever and funny!": "哈哈哈！既聪明又好笑！",
        "Haha! I'd say that's a common name for it.": "哈哈！这名字倒挺常见。",
        "Kinky! HAHA!": "真重口！哈哈！",
        "Haha! Funny, but also gross depending on who played the card.": "哈哈！挺好笑，不过要看是谁出的牌，也可能很恶心。",
        "HAHAHA! Not Grandpa!": "哈哈哈！爷爷可不行！",
        "Hahaha! Oh, no. Not Susan! I won't be able to look her in the eyes now.": "哈哈哈！哦不，不能是苏珊！以后我都没法直视她了。",
        "Hahaha! Who the hell played this one!? Oh my God!": "哈哈哈！这张到底是谁出的！？天啊！",
        "Haha! I'm highly skeptical that it would.": "哈哈！我非常怀疑它有没有用。",
        "Haha! I think this game is enough for this party.": "哈哈！我觉得这场派对有这个游戏就够热闹了。",
        "BAHAHA! Gross!": "哈哈哈！恶心！",
        "Haha! Hey! Me too!": "哈哈！嘿！我也是！",
        "Hahaha! Yes, that would be it.": "哈哈哈！对，就是这个。",
        "Haha! Who would have thought the professor wouldn't enjoy that?": "哈哈！谁能想到教授会不喜欢这个？",
        "Haha! That's so sad.": "哈哈！真可悲。",
        "Haha! Dream big!": "哈哈！梦想远大一点！",
        "HAHA! An obvious but perfect answer.": "哈哈！答案很明显，但完美。",
        "Haha! Yes! Very relatable.": "哈哈！对！太有共鸣了。",
        "Haha! Although topical, let's not have another one of those.": "哈哈！虽然很应景，但可别再来一次了。",
        "Eww! Gross! That's not funny.": "呕！好恶心！一点也不好笑。",
        "Hahaha! Yeah! Fucking spoiled brats.": "哈哈哈！就是！一群被惯坏的小混蛋。",
        "Haha! The immature answers are fucking funny.": "哈哈！幼稚答案就是他妈的好笑。",
        "HAHA! You don't say.": "哈哈！可不是嘛。",
        "Absolutely disgusting. I love it!": "恶心透顶，我喜欢！",
        "Poop? Really? That's so juvenile.": "大便？真的？太幼稚了。",
        "Hahaha! This is so not politically correct. It's so funny.": "哈哈哈！这太政治不正确了，真好笑。",
        "Haha! I sure hope this isn't my future.": "哈哈！但愿这不是我的未来。",
        "Hahaha! An instant classic.": "哈哈哈！瞬间成为经典。",
        "Hahaha! It sure would.": "哈哈哈！肯定会。",
        "Haha! I feel this one was aimed at me. It's sad, but true.": "哈哈！我觉得这张在影射我。虽然心酸，但是真的。",
        "EWW! That's just nasty.": "呕！太恶心了。",
        "Hahaha! As people on dates often do.": "哈哈哈！约会的人确实经常这么干。",
        "Haha! That's so random, but funny.": "哈哈！莫名其妙，但很好笑。",
        "Haha! Yeah, she's very helpful. I'm sure you did.": "哈哈！对，她可真帮忙。我相信你做到了。",
        "Haha! Yes. That would do it.": "哈哈！对，这肯定管用。",
        "That's cute and sexist at the same time.": "既可爱又性别歧视。",
        "Haha. The only thing amusing about that one is that it's grammatically incorrect.": "哈哈。这张唯一好笑的地方，就是语法错了。",
        "Haha! What a cruel answer!": "哈哈！这答案太狠了！",
        "Haha! Am I really going to pick an AIDS joke as the best? I think I might...": "哈哈！我真要把艾滋病笑话选成最佳答案吗？好像真会……",
        "Haha. What a shitty prize.": "哈哈。真是个烂奖品。",
        "Hahaha! Only a million?": "哈哈哈！才一百万？",
        "Hahaha! That's the mother of the year.": "哈哈哈！真是年度最佳母亲。",
        "Haha! I can tell you for a fact that I don't dream of doing that.": "哈哈！我敢肯定，我绝不梦想做那种事。",
        "Haha! Yeah, that would be weird.": "哈哈！对，那会很奇怪。",
        "Hahaha! That's so evil!": "哈哈哈！太坏了！",
        "Haha. Worst date ever!": "哈哈。史上最糟约会！",
        "I bet I know what you did with that banana. Haha!": "我敢说我知道你拿香蕉做了什么。哈哈！",
        "Hahaha! Beggars can't be choosers.": "哈哈哈！乞丐可没资格挑三拣四。",
        "Hahaha! By then, memes will probably be way retro. That's scary to think about.": "哈哈哈！到那时梗图大概都复古了。想想真可怕。",
        "Haha! That's so stupid.": "哈哈！太蠢了。",
        "Hahaha! Mhm!": "哈哈哈！嗯哼！",
        "I hate it when they do that. Haha!": "我最烦别人这么干。哈哈！",
        "HAHA! What a hardcore version of it.": "哈哈！这版本也太硬核了。",
        "No. Not funny. Just horrible.": "不，一点也不好笑，只有可怕。",
        "Haha! That sounds like a fun night.": "哈哈！听起来是个有趣的夜晚。",
        "Haha! Mama better not buy me that.": "哈哈！妈妈最好别给我买那个。",
        "Hahaha! That's so gonna be me.": "哈哈哈！以后肯定就是我。",
        "HAHA! Spot on.": "哈哈！一针见血。",
        "Haha! Yeah, he could afford to pay those.": "哈哈！对，他付得起那些罚单。",
        "Hahaha! Why a hamster!?": "哈哈哈！为什么是仓鼠！？",
        "Haha! That's a good skill to have.": "哈哈！这技能挺实用。",
        "HAHA! Go ahead and build that pipeline. I'll contribute!": "哈哈！尽管把渠道建起来，我来捐！",
        "NO! That's so inappropriate! EWW!": "不！太不合适了！呕！",
        "Hahaha! Yes, you better run!": "哈哈哈！对，你最好快跑！",
        "I suppose you could.": "我想可以吧。",
        "HAHAHA! What a fucking loser!": "哈哈哈！真他妈是个废物！",
        "Really? A fart joke? I hate that it made me laugh. Haha!": "真的？放屁笑话？可恶，我居然笑了。哈哈！",
        "Hahaha! How do you play that? What does meowing do!?": "哈哈哈！这怎么玩？喵叫有什么用！？",
        "Hahaha! What a fatty.": "哈哈哈！真是个胖子。",
        "HAHAHA! It sure isn't.": "哈哈哈！当然不合适。",
        "That's not something I'd recommend doing. Haha!": "我可不建议这么做。哈哈！",
        "Hahaha! Too soon! Right, Derek?": "哈哈哈！现在开这玩笑太早了！对吧，Derek？",
        "Hahaha! I'm no expert, but I don't think that's it.": "哈哈哈！我不是专家，但答案肯定不是这个。",
        "HAHAHA! More like Show and Smell, am I right?": "哈哈哈！不如叫‘展示与闻味’，对吧？",
        "Hahaha! That curse word made it more fun.": "哈哈哈！加上那句脏话更好笑了。",
        "Hahaha! The generosity is unparalleled.": "哈哈哈！这份慷慨无人能比。",
        "Haha! No way! That's a keeper!": "哈哈！不会吧！这张必须留下！",
        "Hahaha! You guys are so weird!": "哈哈哈！你们太怪了！",
        "Hahaha! I guess they ran out of prize money.": "哈哈哈！看来他们的奖金用完了。",
        "Haha! Shaving your pussy, on the other hand... Now that's funny.": "哈哈！不过刮阴毛嘛……这才好笑。",
        "Clearly, we have different red flags.": "显然，我们认定的雷区不一样。",
        "Hahaha! It's so mundane, it's funny.": "哈哈哈！平凡得反而好笑。",
        "Haha! I swear, there's one of those at school. It's crazy!": "哈哈！我发誓学校里就有一个，太疯狂了！",
        "Yes! Haha! Not on my pizza!": "没错！哈哈！别放在我的披萨上！",
        "Hahaha! That sounds like something Derek would bring.": "哈哈哈！听起来像Derek会带来的东西。",
        "Rock, paper, MEOW! Haha! I'd play that.": "石头、布、喵！哈哈！我愿意玩。",
        "Haha! Probably because that essay was too long.": "哈哈！大概是因为论文太长了。",
        "Haha! Not a keeper of a date.": "哈哈！这种约会对象可不能留。",
        "HAHAHA! Best answer ever.": "哈哈哈！史上最佳答案。",
        "Hahaha! NO! Fart jokes aren't supposed to be funny! HAHAHA!": "哈哈哈！不！放屁笑话不该这么好笑！哈哈哈！",
        "HAHA! Why is that so funny? It's so random.": "哈哈！为什么这么好笑？也太莫名其妙了。",
        "Derek... I know this one was you. It's not funny...": "Derek……我知道是你出的，一点也不好笑……",
        "HAHA! That would make me move to Canada. Canada is third-world, right?": "哈哈！这会逼我搬去加拿大。加拿大算第三世界吧？",
        "Haha. Insensitive, but amusing.": "哈哈。虽然冒犯，但挺好笑。",
        "HAHA! I do that all the time.": "哈哈！我一直都这么干。",
        "Haha! That's mean!": "哈哈！太损了！",
        "Haha! That's one bad date.": "哈哈！这约会真够糟的。",
        "Haha! If that won't make you fight for first place, nothing will.": "哈哈！这都不能让你拼命争第一，就没什么能了。",
        "Hahaha! What a numbskull.": "哈哈哈！真是个笨蛋。",
        "Haha! You guys are funny.": "哈哈！你们真逗。",
    }

    def _s3_card_game_cn_replace_text(s):
        if _s3_card_game_prev_replace_text is not None:
            s = _s3_card_game_prev_replace_text(s)
        try:
            active = getattr(renpy.store._preferences, "language", None) in ("chinese", "schinese")
        except Exception:
            active = False
        if active:
            s = _s3_card_game_cn_exact.get(s, s)
        return s

    config.replace_text = _s3_card_game_cn_replace_text
