# Being a DIK S3 Episode 12 B16：补充翻译提取器未收录的任务、Bio 与动态记录。
# 仅替换最终显示文本，不修改剧情条件或返回值。

init 1003 python:
    _s3_ep12_b16_prev_replace_text = config.replace_text

    _s3_ep12_b16_cn_exact = {
        "Now playing": "正在播放",
        "Talk to Jill": "和Jill谈谈",
        "Find Zoey": "找到Zoey",
        "Talk to Sage": "和Sage谈谈",
        "Talk to Maya": "和Maya谈谈",
        "Go to the bathroom": "前往洗手间",
        "Talk to Jade": "和Jade谈谈",
        "Find Dwyane": "找到Dwyane",
        "Play card game": "玩纸牌游戏",
        "Talk to Riona": "和Riona谈谈",
        "Talk to Oscar": "和Oscar谈谈",
        "Head to the DJ table": "前往打碟台",
        "Tara": "Tara",
        "Chad": "Chad",
        "Bianca": "Bianca",
        "Jill": "Jill",
        "Zoey": "Zoey",
        "Josy": "Josy",
        "Maya": "Maya",
        "Isabella": "Isabella",
        "Quinn": "Quinn",
        "Envy": "Envy",
        "Heather": "Heather",
        "Sage": "Sage",
        "Riona": "Riona",
        "Rusty": "Rusty",
        "Micha": "Micha",
        "Sally": "Sally",
        "Troy": "Troy",
        "Jade": "Jade",
        "Lily": "Lily",
        "Derek": "Derek",
        "Ashley": "Ashley",
        "Nikita": "Nikita",
        "Nick": "Nick",
        "Lynette": "Lynette",
        "Sarah": "Sarah",
        "Melanie": "Melanie",
        "Camila": "Camila",
        "Tiffani": "Tiffani",
        "Kylie": "Kylie",
        "Elena": "Elena",
        "John Boy": "John Boy Boy",
        "You": "你",
        "Oscar was salty that I had hooked up with Tara.": "Oscar因为我和Tara亲热过而耿耿于怀。",
        "Chad told me to fuck off without reason at the New Year's Eve party.": "跨年派对上，Chad无缘无故叫我滚开。",
        "Bianca got concerned when I told her I intended to break up with Jill.": "我告诉Bianca自己打算和Jill分手，她很担心。",
        "Bianca got concerned when she thought about how Jill would react to learning about me and Bianca.": "Bianca想到Jill得知我们之间的事后会有什么反应，变得很担心。",
        "Bianca wanted reassurance from me that I wouldn't tell Jill about what had happened between us.": "Bianca要我保证，不会把我们之间发生的事告诉Jill。",
        "After our breakup, Jill didn't want to be around me.": "我们分手后，Jill不愿再和我待在一起。",
        "After what I did with Jade, Jill didn't want to be around me.": "得知我和Jade做过什么后，Jill不愿再和我待在一起。",
        "I put Jill in an awkward position after breaking up with Sage. She didn't know how to be around me and support Sage at the same time.": "我和Sage分手后让Jill陷入了尴尬处境。她不知道该如何既和我相处，又同时支持Sage。",
        "I put Jill in an awkward position after breaking up with Bella. She didn't know how to be around me and support Bella at the same time.": "我和贝拉分手后让Jill陷入了尴尬处境。她不知道该如何既和我相处，又同时支持贝拉。",
        "I put Jill in an awkward position after breaking up with Josy and Maya. She didn't know how to be around me and support them at the same time.": "我和Josy、Maya分手后让Jill陷入了尴尬处境。她不知道该如何既和我相处，又同时支持她们。",
        "Zoey showed up to our New Year's Eve party. I hadn't invited her.": "Zoey来到了我们的跨年派对，但并不是我邀请她的。",
        "Josy was snapping photos of girls in their dresses for her blog.": "Josy正在给穿礼服的女孩们拍照，准备发到博客上。",
        "Maya didn't want to lose my friendship, but didn't know what to do after learning about what I had done with Jade.": "Maya不想失去和我的友谊，但得知我和Jade做过什么后，她不知道该怎么办。",
        "Maya told me she still wanted my friendship, but that it was a hard situation since she's still friends with Sage.": "Maya说她仍想和我做朋友，但她和Sage也是朋友，处境很为难。",
        "Maya told me she still wanted my friendship, but that it was a hard situation since she's still friends with Bella.": "Maya说她仍想和我做朋友，但她和贝拉也是朋友，处境很为难。",
        "Maya told me she still wanted my friendship, but that it was a hard situation since she's still friends with Jill.": "Maya说她仍想和我做朋友，但她和Jill也是朋友，处境很为难。",
        "Bella worked as a chaperone at our New Year's Eve party. She didn't want to speak to me to make our breakup easier.": "贝拉在跨年派对上担任监护人。为了让分手好受一点，她不想和我说话。",
        "Bella worked as a chaperone at our New Year's Eve party. She didn't want to speak to me because of what I did with Jade.": "贝拉在跨年派对上担任监护人。因为我和Jade做过的事，她不想和我说话。",
        "Bella worked as a chaperone at our New Year's Eve party. Bella told me she missed me and that she didn't hold anything against me.": "贝拉在跨年派对上担任监护人。她说自己很想我，也没有怨恨我。",
        "Bella worked as a chaperone at our New Year's Eve party.": "贝拉在我们的跨年派对上担任监护人。",
        "Quinn was in a good mood at the New Year's Eve party. She seemed relaxed and more like herself than she had been for a long time.": "Quinn在跨年派对上心情很好。她很放松，比很长一段时间以来都更像真正的自己。",
        "Nicole wasn't happy with me at the New Year's Eve party.": "跨年派对上，Nicole对我很不满。",
        "Sage told me that Heather still cares about Tommy.": "Sage告诉我，Heather仍然在乎Tommy。",
        "Sage didn't want to be around me anymore.": "Sage不想再和我待在一起。",
        "Sage told me she had a problem with cheaters and had been avoiding me lately. She missed me, but said it was hard to stay friends with me.": "Sage说她无法接受出轨的人，所以最近一直躲着我。她很想我，但觉得很难继续和我做朋友。",
        "I tried to distance myself from Sage. It was hard.": "我试着疏远Sage，这很难受。",
        "Sage told me about her concerns regarding dating someone this close to completing her studies. She didn't want to be tied down after college.": "Sage告诉我，她担心在即将毕业时认真谈恋爱。她不想毕业后被感情束缚。",
        "Riona showed up at the New Year's Eve party. She had tried to hide her scars and bruises as best she could.": "Riona来到了跨年派对，并尽力遮住身上的伤疤和瘀青。",
        "Rusty has been cheating with Micha on my friend Dwyane.": "Rusty一直背着我的朋友Dwyane和Micha偷情。",
        "Micha has been cheating on Dwyane with Rusty.": "Micha一直背着Dwyane和Rusty偷情。",
        "Sally was pleased when she realized that I thought of her as my friend.": "Sally发现我把她当朋友后很高兴。",
        "Troy told me that Chad was feeling paranoid after receiving another threatening letter.": "Troy告诉我，Chad又收到一封恐吓信后变得疑神疑鬼。",
        "I told Jade about my relationship with Zoey.": "我把自己和Zoey的关系告诉了Jade。",
        "Jade put me to the test at the New Year's Eve party. She wanted to see how much our fling meant to me.": "Jade在跨年派对上考验了我，想知道我们的暧昧对我究竟有多重要。",
        "Lily has distanced herself from me.": "Lily疏远了我。",
        "Derek bet me $10 that he could get laid wearing some stupid New Year's Eve-themed glasses.": "Derek和我赌了10美元，说自己戴着那副愚蠢的跨年眼镜也能睡到女人。",
        "It finally happened. Derek and Ashley got together at the New Year's Eve party.": "终于发生了。Derek和Ashley在跨年派对上走到了一起。",
        "Rusty felt guilty about having sex with Micha now that he saw her with Dwyane at the party.": "Rusty在派对上看到Micha和Dwyane在一起后，为自己与Micha上床感到内疚。",
        "Rusty got into a fight with Dwyane after confessing that he had sex with Micha. I chose to stay behind to check up on Rusty after.": "Rusty承认自己和Micha上过床后，与Dwyane打了起来。事后我留下来查看Rusty的情况。",
        "Rusty got into a fight with Dwyane after confessing that he had sex with Micha. I chose to check up on Dwyane after the fight.": "Rusty承认自己和Micha上过床后，与Dwyane打了起来。事后我去查看Dwyane的情况。",
        "Nikita and I almost kissed at the New Year's Eve party. We flirted with each other and had an enjoyable conversation.": "我和Nikita在跨年派对上差点接吻。我们互相调情，也聊得很愉快。",
        "Nick asked me to forgive him for his outburst. I chose to give him another chance.": "Nick为自己的爆发请求原谅，我选择再给他一次机会。",
        "Nick asked me to forgive him for his outburst. I chose not to give him another chance.": "Nick为自己的爆发请求原谅，我选择不再给他机会。",
        "During a drinking game, Quinn outed me as a slut in front of everyone at the New Year's Eve party.": "跨年派对的喝酒游戏中，Quinn当着众人的面揭露我是个滥交鬼。",
        "During a drinking game, Quinn tried to embarrass me in front of everyone at the New Year's Eve party.": "跨年派对的喝酒游戏中，Quinn试图当众让我难堪。",
        "Jill discovered that her family's house was in the background of my mom's picture with her friends.": "Jill发现，我妈妈和朋友合照的背景正是她家的房子。",
        "Bianca discovered that her aunt was in my mom's picture with her friends.": "Bianca发现，她姑姑也在我妈妈和朋友的合照中。",
        "Jill's house seemed to be connected to Mom in some way.": "Jill家的房子似乎和妈妈有某种联系。",
        "I chose to stay friends with Zoey.": "我选择继续和Zoey做朋友。",
        "I chose to end my friendship with Zoey.": "我选择结束和Zoey的友谊。",
        "Josy tried to be supportive of me after my breakup with Bella.": "我和贝拉分手后，Josy试着支持我。",
        "Josy tried to be supportive of me after my breakup with Sage.": "我和Sage分手后，Josy试着支持我。",
        "Josy tried to be supportive of me after my breakup with Jill.": "我和Jill分手后，Josy试着支持我。",
        "You had sex with Jade during the New Year's Eve party in episode 12.": "你在第12集的跨年派对上和Jade发生了关系。",
        "During the New Year's Eve party, I ended up having sex with Jade at midnight.": "跨年派对午夜时，我最终和Jade发生了关系。",
        "During the New Year's Eve party, I kissed Riona at midnight.": "跨年派对午夜时，我吻了Riona。",
        "During the New Year's Eve party, I kissed Quinn at midnight.": "跨年派对午夜时，我吻了Quinn。",
        "During the New Year's Eve party, I kissed Nicole at midnight.": "跨年派对午夜时，我吻了Nicole。",
        "During the New Year's Eve party, I spent midnight next to Lily.": "跨年派对午夜时，我陪在Lily身边。",
        "During the New Year's Eve party, I kissed Nikita at midnight.": "跨年派对午夜时，我吻了Nikita。",
        "During the New Year's Eve party, I kissed Zoey at midnight.": "跨年派对午夜时，我吻了Zoey。",
        "During the New Year's Eve party, I spent midnight next to Sally.": "跨年派对午夜时，我陪在Sally身边。",
        "During the New Year's Eve party, I kissed Sally at midnight.": "跨年派对午夜时，我吻了Sally。",
        "During the New Year's Eve party, I kissed Sarah at midnight.": "跨年派对午夜时，我吻了Sarah。",
        "During the New Year's Eve party, I kissed Melanie at midnight.": "跨年派对午夜时，我吻了Melanie。",
        "During the New Year's Eve party, I spent a moment with Bianca near midnight.": "跨年派对临近午夜时，我和Bianca独处了一会儿。",
        "During the New Year's Eve party, I kissed Camila at midnight.": "跨年派对午夜时，我吻了Camila。",
        "During the New Year's Eve party, I kissed Bella at midnight.": "跨年派对午夜时，我吻了贝拉。",
        "During the New Year's Eve party, I ended the night together with Josy.": "跨年派对结束时，我和Josy在一起。",
        "During the New Year's Eve party, I ended the night together with Maya.": "跨年派对结束时，我和Maya在一起。",
        "During the New Year's Eve party, I ended the night together with Josy & Maya.": "跨年派对结束时，我和Josy、Maya在一起。",
        "During the New Year's Eve party, I kissed Jill at midnight. I told her that I loved her, and she reciprocated.": "跨年派对午夜时，我吻了Jill。我告诉她自己爱她，她也回应了这份感情。",
        "During the New Year's Eve party, I kissed Jill at midnight. I told her that I loved her, but she didn't reciprocate.": "跨年派对午夜时，我吻了Jill。我告诉她自己爱她，但她没有回应。",
        "During the New Year's Eve party, I kissed Jill at midnight.": "跨年派对午夜时，我吻了Jill。",
        "During the New Year's Eve party, I spent midnight alone.": "跨年派对午夜时，我独自一人。",
        "During the New Year's Eve party, I kissed Mia, Erin, and Tiffani at midnight.": "跨年派对午夜时，我吻了Mia、Erin和Tiffani。",
        "I broke up with Sage during the New Year's Eve party.": "我在跨年派对上和Sage分手了。",
        "Sage broke up with me during the New Year's Eve party. She wasn't in love with me and didn't see our relationship lasting past her graduation.": "Sage在跨年派对上和我分手了。她并不爱我，也不认为我们的关系能维持到毕业以后。",
        "Sage broke up with me during the New Year's Eve party. My friendship with Zoey was too much for her to handle.": "Sage在跨年派对上和我分手了。她无法接受我和Zoey的友谊。",
        "During the New Year's Eve party, I had sex with Sage at midnight.": "跨年派对午夜时，我和Sage发生了关系。",
        "During the New Year's Eve party, I had sex with Sage at midnight. Sage told me that she loved me.": "跨年派对午夜时，我和Sage发生了关系。Sage告诉我她爱我。",
        "You had sex with Sage during the New Year's Eve party in episode 12.": "你在第12集的跨年派对上和Sage发生了关系。",
        "Jill broke up with me after learning about my extensive history with girls on campus. I confessed that my heart wasn't fully in our relationship.": "Jill得知我在校园里和许多女孩的过往后，与我分手了。我承认自己没有全心投入这段关系。",
        "Jill broke up with me after learning about my extensive history with girls on campus. It was too much for her to handle.": "Jill得知我在校园里和许多女孩的过往后，与我分手了。这一切让她无法承受。",
        "I broke up with Jill during the New Year's Eve party. I confessed that my heart wasn't fully in our relationship.": "我在跨年派对上和Jill分手了，并承认自己没有全心投入这段关系。",
        "Jill supported me after Quinn tried to embarrass me with her drinking game.": "Quinn试图用喝酒游戏让我难堪后，Jill支持了我。",
        "Bella supported me despite learning that my history with girls on campus was extensive.": "贝拉得知我在校园里和许多女孩都有过往后，仍然选择支持我。",
        "Bella supported me after Quinn tried to embarrass me with her drinking game.": "Quinn试图用喝酒游戏让我难堪后，贝拉支持了我。",
        "Jill and I had sex in the preps' mansion after the New Year's Eve party.": "跨年派对后，我和Jill在富家子弟的豪宅里发生了关系。",
        "You had sex with Jill in the preps' mansion after the New Year's Eve party in episode 12.": "你在第12集跨年派对后，和Jill在富家子弟的豪宅里发生了关系。",
        "Kylie apologized for blaming me for what happened to her sister.": "Kylie为把姐姐遭遇的事怪到我头上而道歉。",
        "I had sex with Sally in her dorm after the New Year's Eve party.": "跨年派对后，我和Sally在她的宿舍里发生了关系。",
        "You had sex with Sally in her dorm after the New Year's Eve party in episode 12.": "你在第12集跨年派对后，和Sally在她的宿舍里发生了关系。",
        "You had sex with Bella in the locker room at the New Year's Eve party in episode 12.": "你在第12集跨年派对上，和贝拉在更衣室里发生了关系。",
        "Bella and I had sex in the locker room at the New Year's Eve party. We thought we heard someone in the room with us.": "跨年派对上，我和贝拉在更衣室里发生了关系。我们以为听见房间里还有别人。",
        "Bella and I had sex in the locker room at the New Year's Eve party.": "跨年派对上，我和贝拉在更衣室里发生了关系。",
        "Zoey and I had sex after the New Year's Eve party.": "跨年派对后，我和Zoey发生了关系。",
        "You had sex with Zoey in your room after the New Year's Eve party in episode 12.": "你在第12集跨年派对后，和Zoey在自己的房间里发生了关系。",
        "I decided to ditch Quinn after she tried to embarrass me at the New Year's Eve party with her drinking game.": "Quinn试图在跨年派对的喝酒游戏中让我难堪后，我决定甩掉她。",
        "Despite her attempt to embarrass me at the New Year's Eve party, I decided I wanted to be with Quinn.": "尽管Quinn试图在跨年派对上让我难堪，我还是决定和她在一起。",
        "Quinn and I had sex behind the DJ booth at the New Year's Eve party.": "跨年派对上，我和Quinn在DJ台后面发生了关系。",
        "You had sex with Quinn behind the DJ booth in episode 12.": "你在第12集和Quinn在DJ台后面发生了关系。",
        "Riona wasn't enjoying the New Year's Eve party, and I tried to support her.": "Riona在跨年派对上过得并不开心，我试着支持她。",
        "Oscar got mad at me because Tara drank during Quinn's drinking game.": "Tara在Quinn的喝酒游戏中喝了酒，Oscar因此对我发火。",
        "Elena asked me if I wanted to have sex with her in front of John Boy.": "Elena问我想不想当着John Boy Boy的面和她做爱。",
        "Josy and Maya decided they wanted to take a break from their relationship.": "Josy和Maya决定暂时中止她们的感情关系。",
        "During the New Year's Eve party, I broke up with Josy and Maya.": "跨年派对上，我和Josy、Maya分手了。",
        "During the New Year's Eve party, I couldn't decide between Josy and Maya and ended up taking a break from both of them.": "跨年派对上，我无法在Josy和Maya之间作出选择，最终和两人都暂时分开。",
        "During the New Year's Eve party, I decided to continue my relationship with Josy.": "跨年派对上，我决定继续和Josy交往。",
        "During the New Year's Eve party, I decided to continue my relationship without Maya.": "跨年派对上，我决定在没有Maya的情况下继续这段关系。",
        "During the New Year's Eve party, I decided to continue my relationship without Josy.": "跨年派对上，我决定在没有Josy的情况下继续这段关系。",
        "During the New Year's Eve party, I decided to continue my relationship with Maya.": "跨年派对上，我决定继续和Maya交往。",
        "Josy and Maya decided they wanted to be friends instead of in a relationship with each other.": "Josy和Maya决定不再彼此交往，退回朋友关系。",
        "During the New Year's Eve party, I decided to enter into a relationship with Maya.": "跨年派对上，我决定和Maya正式交往。",
        "During the New Year's Eve party, I decided to enter into a relationship with Josy.": "跨年派对上，我决定和Josy正式交往。",
        "I fucked Elena in front of John Boy during the New Year's Eve party.": "跨年派对上，我当着John Boy Boy的面操了Elena。",
        "You had sex with Elena in her room in episode 12.": "你在第12集和Elena在她的房间里发生了关系。",
    }

    def _s3_ep12_b16_cn_replace_text(s):
        if _s3_ep12_b16_prev_replace_text is not None:
            s = _s3_ep12_b16_prev_replace_text(s)
        try:
            active = getattr(renpy.store._preferences, "language", None) in ("chinese", "schinese")
        except Exception:
            active = False
        if active:
            s = _s3_ep12_b16_cn_exact.get(s, s)
        return s

    config.replace_text = _s3_ep12_b16_cn_replace_text
